In [26]:
import pandas as pd

In [27]:
countries = pd.read_csv("../database/FAOSTAT_data_7-13-2025.csv", encoding='utf-8', dtype=str)
countries.head()

,Country Group Code,Country Group,Group M49 Code,Country Code,Country,M49 Code,ISO2 Code,ISO3 Code
0,5100,Africa,002,107,Côte d'Ivoire,384,CI,CIV
1,5100,Africa,002,114,Kenya,404,KE,KEN
2,5100,Africa,002,122,Lesotho,426,LS,LSO
3,5100,Africa,002,123,Liberia,430,LR,LBR
4,5100,Africa,002,124,Libya,434,LY,LBY

In [28]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2426 entries, 0 to 2425
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Group Code  2426 non-null   object
 1   Country Group       2426 non-null   object
 2   Group M49 Code      1893 non-null   object
 3   Country Code        2426 non-null   object
 4   Country             2426 non-null   object
 5   M49 Code            2326 non-null   object
 6   ISO2 Code           2326 non-null   object
 7   ISO3 Code           2334 non-null   object
dtypes: object(8)
memory usage: 151.8+ KB

In [29]:
countries['Country Group'].unique()

array(['Africa', 'All Donors', 'Americas', 'Annex I countries',
       'Antarctic Region', 'Asia', 'Australia and New Zealand',
       'Bilateral Donors', 'Bilateral Recipients', 'Caribbean',
       'Caucasus and Central Asia', 'Central America', 'Central Asia',
       'Central Asia and Southern Asia', 'Eastern Africa', 'Eastern Asia',
       'Eastern Asia (excluding Japan and China)',
       'Eastern Asia and South-eastern Asia', 'Eastern Europe', 'Europe',
       'Europe, Northern America, Australia and New Zealand',
       'European Union (27)', 'Land Locked Developing Countries (LLDCs)',
       'Latin America', 'Latin America and the Caribbean',
       'Least Developed Countries (LDCs)',
       'Low Income Food Deficit Countries (LIFDCs)', 'Melanesia',
       'Micronesia', 'Middle Africa', 'Multilateral Donors',
       'Net Food Importing Developing Countries (NFIDCs)',
       'Non-Annex I countries', 'North and Central America',
       'Northern Africa', 'Northern Africa (excluding Sudan)',
       'Northern America', 'Northern America and Europe',
       'Northern Europe', 'Oceania',
       'Oceania excluding Australia and New Zealand', 'OECD', 'Polynesia',
       'Private Donors', 'Small Island Developing States (SIDS)',
       'South America', 'South-eastern Asia', 'Southern Africa',
       'Southern Asia', 'Southern Asia (excluding India)',
       'Southern Europe', 'Sub-Saharan Africa',
       'Sub-Saharan Africa (including Sudan)', 'Western Africa',
       'Western Asia',
       'Western Asia (exc. Armenia, Azerbaijan, Cyprus, Israel and Georgia)',
       'Western Asia and Northern Africa', 'Western Europe', 'World'],
      dtype=object)

In [30]:
# reduce list to countries in "world" group and select name and ISO3 identifier columns
countries_list = countries.loc[countries["Country Group"] == 'World'][['Country','ISO3 Code', 'Country Group']]
countries_dup = countries_list[countries_list['Country'].duplicated()]
countries_dup

Empty DataFrame
Columns: [Country, ISO3 Code, Country Group]
Index: []

In [31]:
# identify duplicate ISO3 identifiers
ISO3_dup = countries_list[countries_list['ISO3 Code'].duplicated()]
ISO3_dup

Empty DataFrame
Columns: [Country, ISO3 Code, Country Group]
Index: []

In [33]:
# Identify unique country names in "World" countries list
country = countries_list['Country'].unique()
country

array(['Armenia', 'Australia', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       "Côte d'Ivoire", 'Kazakhstan', 'Jamaica', 'Austria', 'Japan',
       'Johnston Island', 'Jordan', 'Kyrgyzstan', 'Kenya', 'Cambodia',
       "Democratic People's Republic of Korea", 'Republic of Korea',
       'Kuwait', 'Latvia', 'Bahamas', "Lao People's Democratic Republic",
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Marshall Islands', 'China, Macao SAR', 'Madagascar',
       'Bahrain', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Midway Island',
       'Barbados', 'Monaco', 'Mongolia', 'Montserrat', 'Morocco',
       'Mozambique', 'Micronesia (Federated States of)',
       'Republic of Moldova', 'Namibia', 'Nauru', 'Nepal',
       'Belgium-Luxembourg', 'Netherlands (Kingdom of the)',
       'Netherlands Antilles (former)', 'New Caledonia',
       'North Macedonia', 'Vanuatu', 'New Zealand', 'Nicaragua', 'Niger',
       'Nigeria', 'Bangladesh', 'Niue', 'Norfolk Island', 'Norway',
       'Northern Mariana Islands', 'Pacific Islands Trust Territory',
       'Pakistan', 'Panama', 'Czechia', 'Papua New Guinea', 'Paraguay',
       'Bermuda', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal',
       'Guinea-Bissau', 'Timor-Leste', 'Puerto Rico', 'Eritrea', 'Qatar',
       'Bhutan', 'Palau', 'Zimbabwe', 'Réunion', 'Romania', 'Rwanda',
       'Russian Federation', 'Serbia and Montenegro',
       'Ascension, Saint Helena and Tristan da Cunha',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Bolivia (Plurinational State of)', 'Saint Pierre and Miquelon',
       'Saint Vincent and the Grenadines', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Seychelles',
       'Sierra Leone', 'Slovenia', 'Slovakia', 'Afghanistan', 'Botswana',
       'Singapore', 'Somalia', 'South Africa', 'Spain', 'Western Sahara',
       'Sudan (former)', 'Suriname', 'Tajikistan', 'Eswatini', 'Brazil',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Turkmenistan',
       'China, Taiwan Province of', 'United Republic of Tanzania',
       'Thailand', 'Togo', 'Tokelau', 'Tonga', 'Aruba',
       'Trinidad and Tobago', 'Oman', 'Tunisia', 'Türkiye',
       'Turks and Caicos Islands', 'United Arab Emirates', 'Uganda',
       'Tuvalu', 'USSR',
       'United Kingdom of Great Britain and Northern Ireland', 'Belize',
       'Ukraine', 'United States of America',
       'United States Minor Outlying Islands', 'Burkina Faso', 'Uruguay',
       'Uzbekistan', 'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Ethiopia', 'British Virgin Islands', 'Chagos Archipelago',
       'United States Virgin Islands', 'Wake Island',
       'Wallis and Futuna Islands', 'Samoa', 'Yemen Ar Rp', 'Yemen Dem',
       'Yugoslav SFR', 'Yemen', 'Solomon Islands',
       'Democratic Republic of the Congo', 'Zambia', 'Unspecified Area',
       'Others (adjustment)', 'Belgium', 'Luxembourg', 'Anguilla',
       'Channel Islands', 'Brunei Darussalam',
       'Svalbard and Jan Mayen Islands', 'Isle of Man', 'Bulgaria',
       'Mayotte', 'South Georgia and the South Sandwich Islands',
       'Serbia', 'Montenegro', 'Guernsey', 'Kosovo', 'Sudan',
       'South Sudan', 'Bonaire, Sint Eustatius and Saba', 'Curaçao',
       'Myanmar', 'Sint Maarten (Dutch part)',
       'Saint Martin (French part)', 'Saint Barthélemy', 'Jersey',
       'Åland Islands', 'Sark', 'Burundi', 'Palestine', 'Albania',
       'Antarctica', 'Bouvet Island', 'Cameroon', 'Canada', 'Cabo Verde',
       'China', 'China (excluding Hong Kong & Macao)', 'Cayman Islands',
       'Central African Republic', 'Sri Lanka', 'Chad', 'Algeria',
       'Chile', 'China, mainland', 'Christmas Island',
       'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Cuba', 'American Samoa', 'Cyprus',
       'Czechoslovakia', 'Azerbaijan', 'Southern Africa, unspecified',
       'Benin', 'Central America, unspecified', 'Caribbean, unspecified',
       'Denmark', 'Developing countries, unspecified', 'Dominica',
       'Melanesia, unspecified', 'Dominican Republic', 'Belarus',
       'Ecuador', 'Egypt', 'Andorra', 'El Salvador',
       'Africa, unspecified', 'Asia, unspecified',
       'Eastern Africa, unspecified', 'Eastern Asia, unspecified',
       'Southern Asia, unspecified', 'Western Asia, unspecified',
       'Caribbean, unspecified (population)', 'Equatorial Guinea',
       'Central Asia, unspecified', 'Europe, unspecified',
       'Middle Africa, unspecified', 'Oceania, unspecified',
       'South America, unspecified', 'Northern Africa, unspecified',
       'Western Africa, unspecified', 'Micronesia, unspecified',
       'Polynesia, unspecified',
       'Northern Europe, unspecified (population)', 'Ethiopia PDR',
       'Southern Europe, unspecified',
       'Western Europe, unspecified (population)',
       'Northern America, unspecified (population)', 'Estonia',
       'Faroe Islands', 'Falkland Islands (Malvinas)', 'Fiji', 'Finland',
       'France', 'Americas, unspecified', 'French Guiana', 'Angola',
       'French Polynesia', 'French Southern Territories', 'Djibouti',
       'Georgia', 'Gabon', 'Gambia', 'Gaza Strip (Palestine)',
       'Germany Nl', 'Germany Fr', 'Germany', 'Antigua and Barbuda',
       'Bosnia and Herzegovina', 'Ghana', 'Gibraltar', 'Kiribati',
       'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam',
       'Guatemala', 'Argentina', 'Guinea', 'Guyana',
       'Heard Island and McDonald Islands', 'Haiti', 'Holy See',
       'Honduras', 'China, Hong Kong SAR', 'Hungary', 'Croatia',
       'Iceland'], dtype=object)

In [34]:
# list of "countries" that need removing from "world" list
countries_out = ('Åland Islands','American Samoa','Anguilla','Antarctica','Aruba','Belgium-Luxembourg',
                'Bonaire, Sint Eustatius and Saba','Bouvet Island','British Virgin Islands',
                'Caribbean, unspecified (population)','Chagos Archipelago', 'Channel Islands','China','Christmas Island',
                'Cocos (Keeling) Islands','Curaçao','Cyprus',"Democratic People's Republic of Korea",'Ethiopia PDR',
                'Falkland Islands (Malvinas)','Faroe Islands','France','French Guiana','French Guyana','French Polynesia',
                'French Southern Territories','Germany Fr','Germany Nl','Gibraltar','Greenland','Guadeloupe',
                'Guam','Guernsey',
                'Heard and McDonald Islands','Iran (Islamic Republic of)', 'Isle of Man','Jersey','Johnston Island','Martinique','Mayotte',
                'Micronesia, unspecified','Midway Island','Montserrat','Myanmar','Netherlands Antilles (former)','New Caledonia',
                'Norfolk Island','Northern America, unspecified (population)','Northern Europe, unspecified (population)',
                'Northern Mariana Islands','Pacific Islands Trust Territory','Pitcairn','Polynesia, unspecified','Puerto Rico',
                'Réunion', 'Russian Federation',
                'Saint Barthélemy','Saint Helena, Ascension and Tristan da Cunha','Saint Martin (French part)',
                'Saint Pierre and Miquelon','Saint-Martin (French part)','Serbia and Montenegro','Sint Maarten (Dutch part)',
                'South America, unspecified','South Georgia and the South Sandwich Islands','Southern Europe, unspecified',
                'Sudan (former)','Svalbard and Jan Mayen Islands','United States Minor Outlying Islands',
                'United States Virgin Islands','USSR','Wake Island','Wallis and Futuna Islands','Western Africa, unspecified',
                'Western Europe, unspecified (population)','Western Sahara','Yemen Ar Rp','Yemen Dem')

In [ ]:
# create lists of small island devoloping countries for removal from analysis
small_islands = countries.loc[countries['Country Group'] == 'Small Island Developing States']
small_islands_list = small_islands['Country'].unique().tolist()