In [2]:
import pandas as pd
from unidecode import unidecode

In [3]:
bilan_alimentaire = pd.read_csv('../database/bilan_alimentaire_2020.csv', dtype=str)
bilan_alimentaire

,Code Domaine,Domaine,Code zone (FAO),Zone,Code Élément,Élément,Code Produit (FAO),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FBS,Bilans Alimentaires (2010-),2,Afghanistan,5511,Production,2734,Viande de Volailles,2020,2020,1000 t,28,I,Valeur imputée,NaN
1,FBS,Bilans Alimentaires (2010-),2,Afghanistan,5611,Importations - quantité,2734,Viande de Volailles,2020,2020,1000 t,36,I,Valeur imputée,NaN
2,FBS,Bilans Alimentaires (2010-),2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2020,2020,1000 t,0,I,Valeur imputée,NaN
3,FBS,Bilans Alimentaires (2010-),2,Afghanistan,5911,Exportations - quantité,2734,Viande de Volailles,2020,2020,1000 t,0,I,Valeur imputée,NaN
4,FBS,Bilans Alimentaires (2010-),2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2020,2020,1000 t,64,I,Valeur imputée,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,5511,Production,2734,Viande de Volailles,2020,2020,1000 t,112,I,Valeur imputée,NaN
1080,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,5611,Importations - quantité,2734,Viande de Volailles,2020,2020,1000 t,1,I,Valeur imputée,NaN
1081,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,5072,Variation de stock,2734,Viande de Volailles,2020,2020,1000 t,0,I,Valeur imputée,NaN
1082,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,5301,Disponibilité intérieure,2734,Viande de Volailles,2020,2020,1000 t,113,I,Valeur imputée,NaN
1083,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,5142,Nourriture,2734,Viande de Volailles,2020,2020,1000 t,113,I,Valeur imputée,NaN

In [4]:
bilan_alimentaire = pd.read_csv('../database/bilan_alimentaire_2020.csv', dtype=str)
def preprocess_bilan_alimentaire_data(bilan_alimentaire):
    bilan_alimentaire = bilan_alimentaire.drop(columns=['Note', 'Description du Symbole', 'Symbole', 'Code année', 'Produit', 'Code Produit (FAO)', 'Domaine', 'Code Domaine', 'Unité'])
    return bilan_alimentaire
bilan_alimentaire = preprocess_bilan_alimentaire_data(bilan_alimentaire)
bilan_alimentaire

,Code zone (FAO),Zone,Code Élément,Élément,Année,Valeur
0,2,Afghanistan,5511,Production,2020,28
1,2,Afghanistan,5611,Importations - quantité,2020,36
2,2,Afghanistan,5072,Variation de stock,2020,0
3,2,Afghanistan,5911,Exportations - quantité,2020,0
4,2,Afghanistan,5301,Disponibilité intérieure,2020,64
...,...,...,...,...,...,...
1079,181,Zimbabwe,5511,Production,2020,112
1080,181,Zimbabwe,5611,Importations - quantité,2020,1
1081,181,Zimbabwe,5072,Variation de stock,2020,0
1082,181,Zimbabwe,5301,Disponibilité intérieure,2020,113
1083,181,Zimbabwe,5142,Nourriture,2020,113

In [5]:
def convert_bilan_alimentaire_to_numeric(bilan_alimentaire):
    bilan_alimentaire['Valeur'] = bilan_alimentaire['Valeur'].astype(float)
    return bilan_alimentaire

bilan_alimentaire_transformed = convert_bilan_alimentaire_to_numeric(bilan_alimentaire)
bilan_alimentaire_transformed

,Code zone (FAO),Zone,Code Élément,Élément,Année,Valeur
0,2,Afghanistan,5511,Production,2020,28.0
1,2,Afghanistan,5611,Importations - quantité,2020,36.0
2,2,Afghanistan,5072,Variation de stock,2020,0.0
3,2,Afghanistan,5911,Exportations - quantité,2020,0.0
4,2,Afghanistan,5301,Disponibilité intérieure,2020,64.0
...,...,...,...,...,...,...
1079,181,Zimbabwe,5511,Production,2020,112.0
1080,181,Zimbabwe,5611,Importations - quantité,2020,1.0
1081,181,Zimbabwe,5072,Variation de stock,2020,0.0
1082,181,Zimbabwe,5301,Disponibilité intérieure,2020,113.0
1083,181,Zimbabwe,5142,Nourriture,2020,113.0

In [6]:
def transform_bilan_data(bilan_alimentaire):
    grouper_lignes = bilan_alimentaire.groupby(['Code zone (FAO)', 'Zone', 'Élément'], as_index=False).sum()
    return grouper_lignes
grouper_lignes = transform_bilan_data(bilan_alimentaire_transformed)
grouper_lignes

,Code zone (FAO),Zone,Élément,Code Élément,Année,Valeur
0,1,Arménie,Disponibilité intérieure,5301,2020,46.0
1,1,Arménie,Exportations - quantité,5911,2020,0.0
2,1,Arménie,Importations - quantité,5611,2020,33.0
3,1,Arménie,Nourriture,5142,2020,46.0
4,1,Arménie,Production,5511,2020,12.0
...,...,...,...,...,...,...
1079,99,Islande,Exportations - quantité,5911,2020,0.0
1080,99,Islande,Importations - quantité,5611,2020,2.0
1081,99,Islande,Nourriture,5142,2020,11.0
1082,99,Islande,Production,5511,2020,9.0
1083,99,Islande,Variation de stock,5072,2020,0.0

In [7]:
def transform_bilan_alim_data(grouper_lignes):
    bilan_alimentaire = grouper_lignes.pivot(index=['Code zone (FAO)','Zone'], columns='Élément', values='Valeur')
    bilan_alimentaire = bilan_alimentaire.reset_index()
    bilan_alimentaire = bilan_alimentaire.rename(columns={'Code zone (FAO)': 'country_code'})
    return bilan_alimentaire

bilan_alimentaire_transformed = transform_bilan_alim_data(grouper_lignes)
bilan_alimentaire_transformed

Élément,country_code,Zone,Disponibilité intérieure,Exportations - quantité,Importations - quantité,Nourriture,Production,Variation de stock
0,1,Arménie,46.0,0.0,33.0,46.0,12.0,0.0
1,10,Australie,1242.0,42.0,2.0,1242.0,1282.0,0.0
2,100,Inde,4515.0,4.0,0.0,4516.0,4519.0,0.0
3,101,Indonésie,3682.0,0.0,0.0,3682.0,3683.0,1.0
4,102,Iran (République islamique d'),2438.0,6.0,3.0,2439.0,2441.0,0.0
...,...,...,...,...,...,...,...,...
184,95,Honduras,205.0,1.0,16.0,205.0,190.0,0.0
185,96,Chine - RAS de Hong-Kong,404.0,90.0,558.0,404.0,34.0,98.0
186,97,Hongrie,312.0,233.0,84.0,268.0,521.0,60.0
187,98,Croatie,68.0,16.0,25.0,68.0,70.0,12.0
188,99,Islande,11.0,0.0,2.0,11.0,9.0,0.0

In [8]:
def transform_regex_bilan_alimentaire(bilan_alimentaire_transformed):
    bilan_alimentaire_transformed.columns = bilan_alimentaire_transformed.columns.str.replace(' ', '_', regex=False)
    bilan_alimentaire_transformed.columns = bilan_alimentaire_transformed.columns.str.lower()
    bilan_alimentaire_transformed.columns = [unidecode(col) for col in bilan_alimentaire_transformed.columns]
    return bilan_alimentaire_transformed

bilan_alimentaire_transformed = transform_regex_bilan_alimentaire(bilan_alimentaire_transformed)

In [10]:
bilan_alimentaire_transformed.columns

Index(['country_code', 'zone', 'disponibilite_interieure',
       'exportations_-_quantite', 'importations_-_quantite', 'nourriture',
       'production', 'variation_de_stock'],
      dtype='object')

In [ ]:
def save_transformed_bilan_alimentaire_data(bilan_alimentaire_transformed):
    bilan_alimentaire_transformed.to_csv('../export/bilan_alimentaire_2020.csv', index=False, encoding='utf-8')
    print("Bilan alimentaire data transformed and saved successfully.")

save_transformed_bilan_alimentaire_data(bilan_alimentaire_transformed)

Bilan alimentaire data transformed and saved successfully.