In [1]:
import pandas as pd
from unidecode import unidecode

In [2]:
culture_prod_poulet = pd.read_csv('../database/culture_produits_poulet_2020.csv', dtype=str)
culture_prod_poulet

,Code Domaine,Domaine,Code zone (FAO),Zone,Code Élément,Élément,Code Produit (FAO),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,QCL,Cultures et produits animaux,2,Afghanistan,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,12848,E,Valeur estimée,NaN
1,QCL,Cultures et produits animaux,202,Afrique du Sud,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,168993,I,Valeur imputée,NaN
2,QCL,Cultures et produits animaux,3,Albanie,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,6774,A,Chiffre officiel,NaN
3,QCL,Cultures et produits animaux,4,Algérie,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,192589,I,Valeur imputée,NaN
4,QCL,Cultures et produits animaux,79,Allemagne,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,159118,A,Chiffre officiel,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,QCL,Cultures et produits animaux,236,Venezuela (République bolivarienne du),5112,Réserves,1057,Poulets,2020,2020,1000 têtes,131047,I,Valeur imputée,NaN
190,QCL,Cultures et produits animaux,237,Viet Nam,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,409500,A,Chiffre officiel,NaN
191,QCL,Cultures et produits animaux,249,Yémen,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,69039,I,Valeur imputée,NaN
192,QCL,Cultures et produits animaux,251,Zambie,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,41077,I,Valeur imputée,NaN
193,QCL,Cultures et produits animaux,181,Zimbabwe,5112,Réserves,1057,Poulets,2020,2020,1000 têtes,16200,E,Valeur estimée,NaN

In [3]:
culture_prod_poulet = pd.read_csv('../database/culture_produits_poulet_2020.csv', dtype=str)
def preprocess_culture_prod_poulet_data(culture_prod_poulet):
    culture_prod_poulet = culture_prod_poulet.drop(columns=['Note', 'Description du Symbole', 'Symbole', 'Code année', 'Produit', 'Code Produit (FAO)', 'Domaine', 'Code Domaine', 'Unité'])
    return culture_prod_poulet
culture_prod_poulet = preprocess_culture_prod_poulet_data(culture_prod_poulet)
culture_prod_poulet

,Code zone (FAO),Zone,Code Élément,Élément,Année,Valeur
0,2,Afghanistan,5112,Réserves,2020,12848
1,202,Afrique du Sud,5112,Réserves,2020,168993
2,3,Albanie,5112,Réserves,2020,6774
3,4,Algérie,5112,Réserves,2020,192589
4,79,Allemagne,5112,Réserves,2020,159118
...,...,...,...,...,...,...
189,236,Venezuela (République bolivarienne du),5112,Réserves,2020,131047
190,237,Viet Nam,5112,Réserves,2020,409500
191,249,Yémen,5112,Réserves,2020,69039
192,251,Zambie,5112,Réserves,2020,41077
193,181,Zimbabwe,5112,Réserves,2020,16200

In [4]:
def convert_culture_prod_poulet_to_numeric(culture_prod_poulet):
    culture_prod_poulet['Valeur'] = culture_prod_poulet['Valeur'].astype(float)
    return culture_prod_poulet

culture_prod_poulet_transformed = convert_culture_prod_poulet_to_numeric(culture_prod_poulet)
culture_prod_poulet_transformed

,Code zone (FAO),Zone,Code Élément,Élément,Année,Valeur
0,2,Afghanistan,5112,Réserves,2020,12848.0
1,202,Afrique du Sud,5112,Réserves,2020,168993.0
2,3,Albanie,5112,Réserves,2020,6774.0
3,4,Algérie,5112,Réserves,2020,192589.0
4,79,Allemagne,5112,Réserves,2020,159118.0
...,...,...,...,...,...,...
189,236,Venezuela (République bolivarienne du),5112,Réserves,2020,131047.0
190,237,Viet Nam,5112,Réserves,2020,409500.0
191,249,Yémen,5112,Réserves,2020,69039.0
192,251,Zambie,5112,Réserves,2020,41077.0
193,181,Zimbabwe,5112,Réserves,2020,16200.0

In [5]:
def transform_culture_prod_poulet_data(culture_prod_poulet):
    grouper_lignes = culture_prod_poulet.groupby(['Code zone (FAO)', 'Zone', 'Élément'], as_index=False).sum()
    return grouper_lignes
grouper_lignes = transform_culture_prod_poulet_data(culture_prod_poulet_transformed )
grouper_lignes

,Code zone (FAO),Zone,Élément,Code Élément,Année,Valeur
0,1,Arménie,Réserves,5112,2020,4396.0
1,10,Australie,Réserves,5112,2020,100894.0
2,100,Inde,Réserves,5112,2020,824722.0
3,101,Indonésie,Réserves,5112,2020,3570142.0
4,102,Iran (République islamique d'),Réserves,5112,2020,1010445.0
...,...,...,...,...,...,...
189,95,Honduras,Réserves,5112,2020,47038.0
190,96,Chine - RAS de Hong-Kong,Réserves,5112,2020,4392.0
191,97,Hongrie,Réserves,5112,2020,30874.0
192,98,Croatie,Réserves,5112,2020,11360.0
193,99,Islande,Réserves,5112,2020,222.0

In [6]:
def transform_culture_prod_poulet_data(grouper_lignes):
    culture_prod_poulet = grouper_lignes.pivot(index=['Code zone (FAO)','Zone'], columns='Élément', values='Valeur')
    culture_prod_poulet = culture_prod_poulet.reset_index()
    culture_prod_poulet = culture_prod_poulet.rename(columns={'Code zone (FAO)': 'country_code'})
    return culture_prod_poulet

culture_prod_poulet_transformed = transform_culture_prod_poulet_data(grouper_lignes)
culture_prod_poulet_transformed

Élément country_code                            Zone   Réserves
0                  1                         Arménie     4396.0
1                 10                       Australie   100894.0
2                100                            Inde   824722.0
3                101                       Indonésie  3570142.0
4                102  Iran (République islamique d')  1010445.0
..               ...                             ...        ...
189               95                        Honduras    47038.0
190               96        Chine - RAS de Hong-Kong     4392.0
191               97                         Hongrie    30874.0
192               98                         Croatie    11360.0
193               99                         Islande      222.0

[194 rows x 3 columns]

In [7]:
def transform_regex_culture_prod_poulet(culture_prod_poulet_transformed):
    culture_prod_poulet_transformed.columns = culture_prod_poulet_transformed.columns.str.replace(' ', '_', regex=False)
    culture_prod_poulet_transformed.columns = culture_prod_poulet_transformed.columns.str.lower()
    culture_prod_poulet_transformed.columns = [unidecode(col) for col in culture_prod_poulet_transformed.columns]
    return culture_prod_poulet_transformed

culture_prod_poulet_transformed = transform_regex_culture_prod_poulet(culture_prod_poulet_transformed)

In [8]:
def save_transformed_culture_prod_poulet_data(culture_prod_poulet_transformed):
    culture_prod_poulet_transformed.to_csv('../export/culture_prod_poulet_2020.csv', index=False, encoding='utf-8')
    print("Culture production poulet data transformed and saved successfully.")

save_transformed_culture_prod_poulet_data(culture_prod_poulet_transformed)

Culture production poulet data transformed and saved successfully.