In [1]:
import pandas as pd

In [2]:
indices_commerciaux = pd.read_csv("../export/indices_commerciaux_2020.csv", sep=",", dtype={"country_code": str})
population = pd.read_csv("../export/population_2020.csv", sep=",", dtype={"country_code": str})
securite_alimentaire = pd.read_csv("../export/securite_alimentaire_2020.csv", sep=",", dtype={"country_code": str})
groupe_pays = pd.read_csv("../export/groupe_pays.csv", sep=",", dtype={"code_pays": str})
indicateur_emploi = pd.read_csv("../export/indicateur_emploi_2020.csv", sep=",", dtype={"country_code": str})
valeur_prod_agricole = pd.read_csv("../export/valeur_prod_agricole_2020.csv", sep=",", dtype={"country_code": str})
culture_prod_poulet = pd.read_csv("../export/culture_prod_poulet_2020.csv", sep=",", dtype={"country_code": str})
bilan_alimentaire = pd.read_csv("../export/bilan_alimentaire_2020.csv", sep=",", dtype={"country_code": str})

In [3]:
indices_commerciaux = indices_commerciaux.drop(columns=[
    "indice_de_valeur_unitaire_a_l'import_(2014-2016_=_100)", 
    "indice_de_valeur_unitaire_a_l'export_(2014-2016_=_100)",
    "indice_de_quantite_d'exportation_(2014-2016_=_100)",
    "indice_de_quantite_d'importation_(2014-2016_=_100)",
    "indice_de_valeur_d'exportation_(2014-2016_=_100)",
    "indice_de_valeur_des_importations_(2014-2016_=_100)",
])
indices_commerciaux

,country_code,zone,valeur_des_exportations_-_prix_periode_de_reference,valeur_des_exportations_-_quantite_periode_de_reference,valeur_des_importations_-_prix_periode_de_reference,valeur_des_importations_-_quantite_periode_de_reference
0,1,Arménie,394790.0,285986.0,848369.0,520384.0
1,10,Australie,25054864.0,35414918.0,10178035.0,14581857.0
2,100,Inde,31528384.0,26102565.0,21229798.0,20967386.0
3,101,Indonésie,34787544.0,30565911.0,19865540.0,13710859.0
4,102,Iran (République islamique d'),7868343.0,3309283.0,9822524.0,9349679.0
...,...,...,...,...,...,...
190,95,Honduras,2447891.0,2110506.0,1442149.0,1301384.0
191,96,Chine - RAS de Hong-Kong,3559741.0,11199521.0,13903213.0,22458043.0
192,97,Hongrie,8194725.0,6691580.0,4996786.0,4416827.0
193,98,Croatie,1826101.0,1309198.0,2897383.0,2286200.0
194,99,Islande,49734.0,44752.0,486216.0,410563.0

In [4]:
population = population.drop(columns=["femmes", "hommes", "population_rurale", "population_urbaine"])
population

    country_code                            zone  population_totale
0              1                         Arménie       2.890892e+06
1             10                       Australie       2.574379e+07
2            100                            Inde       1.402618e+09
3            101                       Indonésie       2.748149e+08
4            102  Iran (République islamique d')       8.772344e+07
..           ...                             ...                ...
231           95                        Honduras       1.011964e+07
232           96        Chine - RAS de Hong-Kong       7.490235e+06
233           97                         Hongrie       9.749457e+06
234           98                         Croatie       3.953958e+06
235           99                         Islande       3.666140e+05

[236 rows x 3 columns]

In [5]:
securite_alimentaire.columns
securite_alimentaire = securite_alimentaire.drop(columns=[
    "besoins_energetiques_alimentaires_minimaux_(kcal/personne/jour)", 
    "coefficient_de_variation_de_la_distribution_de_la_consommation_calorique_habituelle_(vraie_valeur)",
    "disponibilite_alimentaire_par_habitant_utilisee_dans_l'estimation_de_la_prevalence_de_la_sous-alimentation_(kcal/personne/jour)",
    "disponibilite_alimentaire_par_habitant_utilisee_dans_l'estimation_de_la_prevalence_de_la_sous-alimentation_(kcal/personne/jour)_(moyenne_sur_3_ans)",
    "disponibilites_moyennes_de_matiere_grasse_(g/personne/jour)_(moyenne_sur_3_ans)",
    "disponibilites_proteines_moyennes_d'origine_animale_(g/personne/jour)_(moyenne_sur_3_ans)",
    "disponibilites_proteiques_moyennes_(g/personne/jour)_(moyenne_sur_3_ans)",
    "incidence_des_pertes_caloriques_au_niveau_de_la_vente_au_detail_(%)",
    "nombre_d'adultes_(18_ans_ou_plus)_obeses_(millions)",
    "nombre_d'enfants_de_moins_de_5_ans_presentant_un_exces_ponderal_(estimation_modelisee)_(millions)",
    "nombre_d'enfants_de_moins_de_5_ans_presentant_un_retard_de_croissance_(estimation_modelisee)_(millions)",
    "nombre_d'enfants_de_moins_de_5_ans_emacies_(millions)",
    "nombre_de_femmes_adultes_en_situation_d'insecurite_alimentaire_grave_(millions)_(moyenne_sur_3_ans)",
    "nombre_de_femmes_adultes_en_situation_d'insecurite_alimentaire_moderee_ou_grave_(millions)_(moyenne_sur_3_ans)",
    "nombre_de_nouveaux-nes_en_insuffisance_ponderale_(millions)",
    "nombre_de_personnes_en_situation_d'insecurite_alimentaire_grave_(millions)_(moyenne_sur_3_ans)",
    "nombre_de_personnes_en_situation_d'insecurite_alimentaire_moderee_ou_grave_(millions)_(moyenne_sur_3_ans)",
    "nombre_de_personnes_sous-alimentees_(millions)_(moyenne_sur_3_ans)",
    "nombre_d'hommes_adultes_en_situation_d'insecurite_alimentaire_moderee_ou_grave_(millions)_(moyenne_sur_3_ans)",
    "part_des_cereales,_des_racines_et_des_tubercules_dans_les_apports_energetiques_alimentaires_(%)_(moyenne_sur_3_ans)",
    "pourcentage_de_la_population_ayant_acces_a_des_services_d'assainissement_geres_en_toute_securite",
    "pourcentage_de_la_population_ayant_acces_a_des_services_d'eau_potable_geres_en_toute_securite",
    "pourcentage_de_la_population_utilisant_au_moins_les_services_d'assainissement_de_base",
    "pourcentage_de_la_population_utilisant_au_moins_les_services_d'eau_de_base",
    "pourcentage_des_enfants_de_moins_de_5_ans_presentant_un_retard_de_croissance_(estimation_modelisee)_(%)",
    "pourcentage_des_enfants_de_moins_de_5_ans_emacies_(%)",
    "pourcentage_des_terres_arables_amenagees_pour_l'irrigation_(%)_(moyenne_sur_3_ans)",
    "prevalence_de_l'allaitement_exclusif_au_sein_du_nourrisson_de_0_a_5_mois",
    "prevalence_de_l'exces_ponderal_chez_l'enfant_de_moins_de_5_ans_(estimation_modelisee)_(%)",
    "prevalence_de_l'insuffisance_ponderale_a_la_naissance_(%)",
    "prevalence_de_l'obesite_chez_l'adulte_(18_ans_ou_plus)",
    "prevalence_de_la_sous-alimentation_(%)_(moyenne_sur_3_ans)",
    "prevalence_de_l'insecurite_alimentaire_grave_-_femmes_adultes_(%)_(moyenne_sur_3_ans)",
    "prevalence_de_l'insecurite_alimentaire_grave_-_hommes_adultes_(%)_(moyenne_sur_3_ans)",
    "prevalence_de_l'insecurite_alimentaire_grave_-_population_totale_(%)_(moyenne_sur_3_ans)",
    "prevalence_de_l'insecurite_alimentaire_moderee_ou_grave_-_femmes_adultes_(%)_(moyenne_sur_3_ans)",
    "prevalence_de_l'insecurite_alimentaire_moderee_ou_grave_-_hommes_adultes_(%)_(moyenne_sur_3_ans)",
    "prevalence_de_l'insecurite_alimentaire_moderee_ou_grave_-_population_totale_(%)_(moyenne_sur_3_ans)",
    "suffisance_des_apports_energetiques_alimentaires_moyens_(%)_(moyenne_sur_3_ans)",
])

securite_alimentaire

,country_code,zone,besoins_energetiques_alimentaires_moyens_(kcal/personne/jour),densite_du_reseau_ferroviaire_(pour_100_km_carres_de_surface_totale_du_pays),"pib_par_habitant,_($_ppa_internationaux_constants_de_2017)",stabilite_politique_et_absence_de_violence/terrorisme_(indice),taux_de_dependance_a_l'egard_des_importations_cerealieres_(%)_(moyenne_sur_3_ans),valeur_des_importations_alimentaires_par_rapport_aux_exportations_totales_de_marchandises_(%)_(moyenne_sur_3_ans),variabilite_des_disponibilites_alimentaires_par_habitant_(kcal/personne/jour)
0,1,Arménie,2420.0,2.3,1.588930e+10,-0.77,85.9,24.0,51.0
1,10,Australie,2493.0,0.0,5.629820e+10,0.86,-163.2,5.0,31.0
2,100,Inde,2325.0,2.1,7.436100e+09,-0.84,-8.9,6.0,20.0
3,101,Indonésie,2311.0,0.0,1.252320e+10,-0.46,15.3,8.0,43.0
4,102,Iran (République islamique d'),2376.0,0.5,1.446860e+10,-1.70,47.8,14.0,37.0
...,...,...,...,...,...,...,...,...,...
199,95,Honduras,2304.0,0.0,5.672200e+09,-0.45,65.3,18.0,8.0
200,96,Chine - RAS de Hong-Kong,2432.0,0.0,6.132840e+10,0.06,100.0,4.0,73.0
201,97,Hongrie,2527.0,8.2,3.593780e+10,0.84,-91.8,4.0,26.0
202,98,Croatie,2492.0,3.0,3.112400e+10,0.61,-51.0,17.0,34.0
203,99,Islande,2561.0,0.0,5.980190e+10,1.37,92.5,10.0,44.0

In [6]:
groupe_pays

,code_groupe_de_pays,groupe_de_pays,code_groupe_m49,code_pays,pays,code_m49,code_iso2,code_iso3
0,5100,Afrique,2.0,107,Côte d'Ivoire,384.0,CI,CIV
1,5100,Afrique,2.0,114,Kenya,404.0,KE,KEN
2,5100,Afrique,2.0,122,Lesotho,426.0,LS,LSO
3,5100,Afrique,2.0,123,Libéria,430.0,LR,LBR
4,5100,Afrique,2.0,124,Libye,434.0,LY,LBY
...,...,...,...,...,...,...,...,...
2421,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,247,Yemen Dém,720.0,F247,F247
2422,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,249,Yémen,887.0,YE,YEM
2423,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,299,Palestine,275.0,F299,PSE
2424,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,608,"Asie de l'Ouest, non spécifié",879.0,F608,F608
2425,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,76,Palestine,274.0,F76,76

In [7]:
indicateur_emploi = indicateur_emploi.rename(columns={"valeur": "indicateur_emploi"})
indicateur_emploi

   country_code                            zone  indicateur_emploi
0             1                         Arménie             361.06
1            10                       Australie             314.85
2           100                            Inde          171201.84
3           102  Iran (République islamique d')            3751.40
4           104                         Irlande              96.47
..          ...                             ...                ...
80            9                       Argentine              44.89
81           95                        Honduras             813.30
82           97                         Hongrie             191.54
83           98                         Croatie              90.35
84           99                         Islande               3.64

[85 rows x 3 columns]

In [8]:
valeur_prod_agricole

,country_code,zone,production_brute_2014-2016_(millier_int$)
0,1,Arménie,22694.0
1,10,Australie,2441665.0
2,100,Inde,8593866.0
3,101,Indonésie,6988395.0
4,102,Iran (République islamique d'),4669888.0
...,...,...,...
163,91,Guyana,81916.0
164,93,Haïti,14813.0
165,95,Honduras,359543.0
166,96,Chine - RAS de Hong-Kong,34299.0
167,99,Islande,17427.0

In [9]:
culture_prod_poulet

    country_code                            zone   reserves
0              1                         Arménie     4396.0
1             10                       Australie   100894.0
2            100                            Inde   824722.0
3            101                       Indonésie  3570142.0
4            102  Iran (République islamique d')  1010445.0
..           ...                             ...        ...
189           95                        Honduras    47038.0
190           96        Chine - RAS de Hong-Kong     4392.0
191           97                         Hongrie    30874.0
192           98                         Croatie    11360.0
193           99                         Islande      222.0

[194 rows x 3 columns]

In [10]:
bilan_alimentaire

,country_code,zone,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
0,1,Arménie,46.0,0.0,33.0,46.0,12.0,0.0
1,10,Australie,1242.0,42.0,2.0,1242.0,1282.0,0.0
2,100,Inde,4515.0,4.0,0.0,4516.0,4519.0,0.0
3,101,Indonésie,3682.0,0.0,0.0,3682.0,3683.0,1.0
4,102,Iran (République islamique d'),2438.0,6.0,3.0,2439.0,2441.0,0.0
...,...,...,...,...,...,...,...,...
184,95,Honduras,205.0,1.0,16.0,205.0,190.0,0.0
185,96,Chine - RAS de Hong-Kong,404.0,90.0,558.0,404.0,34.0,98.0
186,97,Hongrie,312.0,233.0,84.0,268.0,521.0,60.0
187,98,Croatie,68.0,16.0,25.0,68.0,70.0,12.0
188,99,Islande,11.0,0.0,2.0,11.0,9.0,0.0

In [11]:
# Récupérer les sets de country_code
codes_pop = set(population['country_code'])
codes_sec = set(securite_alimentaire['country_code'])
codes_indices = set(indices_commerciaux['country_code'])
codes_indicateur_emploi = set(indicateur_emploi['country_code'])
codes_valeur_prod_agricole = set(valeur_prod_agricole['country_code'])
codes_culture_prod_poulet = set(culture_prod_poulet['country_code'])
codes_bilan_alimentaire = set(bilan_alimentaire['country_code'])

# country_code présents dans population mais pas dans securite_alimentaire
manquants_dans_secu = codes_pop - codes_sec
print("Présents dans population mais pas dans securite_alimentaire :", manquants_dans_secu)

# country_code présents dans securite_alimentaire mais pas dans population
manquants_dans_pop = codes_sec - codes_pop
print("Présents dans securite_alimentaire mais pas dans population :", manquants_dans_pop)

# country_code présents dans indices_commerciaux mais pas dans population
manquants_dans_pop_indices = codes_pop - codes_indices
print("Présents dans population mais pas dans indices_commerciaux :", manquants_dans_pop_indices)

# country_code présents dans population mais pas dans indices_commerciaux
manquants_dans_indices_pop = codes_indices - codes_pop
print("Présents dans indices_commerciaux mais pas dans population :", manquants_dans_indices_pop)

# country_code présents dans population mais pas dans indicateur_emploi
manquants_dans_pop_indicateur_emploi = codes_pop - codes_indicateur_emploi
print("Présents dans population mais pas dans indicateur_emploi :", manquants_dans_pop_indicateur_emploi)

# country_code présents dans indicateur_emploi mais pas dans population
manquants_dans_indicateur_emploi_pop = codes_indicateur_emploi - codes_pop
print("Présents dans indicateur_emploi mais pas dans population :", manquants_dans_indicateur_emploi_pop)

# country_code présents dans population mais pas dans valeur_prod_agricole
manquants_dans_pop_valeur_prod_agricole = codes_pop - codes_valeur_prod_agricole
print("Présents dans population mais pas dans valeur_prod_agricole :", manquants_dans_pop_valeur_prod_agricole) 

# country_code présents dans valeur_prod_agricole mais pas dans population
manquants_dans_valeur_prod_agricole_pop = codes_valeur_prod_agricole - codes_pop
print("Présents dans valeur_prod_agricole mais pas dans population :", manquants_dans_valeur_prod_agricole_pop) 

# country_code présents dans population mais pas dans culture_prod_poulet
manquants_dans_pop_culture_prod_poulet = codes_pop - codes_culture_prod_poulet
print("Présents dans population mais pas dans culture_prod_poulet :", manquants_dans_pop_culture_prod_poulet)

# country_code présents dans culture_prod_poulet mais pas dans population
manquants_dans_culture_prod_poulet_pop = codes_culture_prod_poulet - codes_pop
print("Présents dans culture_prod_poulet mais pas dans population :", manquants_dans_culture_prod_poulet_pop)

# country_code présents dans population mais pas dans bilan_alimentaire
manquants_dans_pop_bilan_alimentaire = codes_pop - codes_bilan_alimentaire
print("Présents dans population mais pas dans bilan_alimentaire :", manquants_dans_pop_bilan_alimentaire)

# country_code présents dans bilan_alimentaire mais pas dans population
manquants_dans_bilan_alimentaire_pop = codes_bilan_alimentaire - codes_pop
print("Présents dans bilan_alimentaire mais pas dans population :", manquants_dans_bilan_alimentaire_pop)

Présents dans population mais pas dans securite_alimentaire : {'259', '281', '135', '22', '142', '190', '88', '94', '278', '282', '192', '163', '280', '65', '87', '258', '36', '240', '224', '82', '125', '239', '270', '182', '243', '205', '140', '69', '64', '264', '279', '187'}
Présents dans securite_alimentaire mais pas dans population : set()
Présents dans population mais pas dans indices_commerciaux : {'259', '281', '135', '22', '142', '190', '180', '88', '94', '278', '282', '192', '145', '163', '280', '85', '351', '127', '65', '87', '17', '258', '36', '240', '224', '82', '218', '125', '239', '270', '182', '243', '6', '5', '177', '205', '140', '69', '264', '279', '187'}
Présents dans indices_commerciaux mais pas dans population : set()
Présents dans population mais pas dans indicateur_emploi : {'235', '281', '233', '278', '282', '227', '66', '114', '16', '91', '46', '74', '181', '351', '236', '8', '146', '127', '61', '175', '87', '17', '165', '159', '47', '200', '194', '212', '118', '108', '213', '209', '250', '6', '197', '177', '14', '249', '205', '264', '179', '131', '187', '72', '37', '178', '217', '107', '75', '90', '32', '35', '163', '221', '280', '168', '3', '65', '89', '45', '101', '272', '125', '207', '270', '109', '243', '5', '158', '188', '259', '120', '39', '13', '22', '132', '190', '41', '191', '52', '94', '96', '157', '193', '145', '195', '85', '144', '166', '229', '123', '33', '149', '258', '7', '219', '156', '93', '12', '182', '222', '226', '117', '4', '64', '279', '136', '135', '238', '49', '55', '88', '185', '277', '273', '2', '160', '201', '192', '128', '53', '124', '129', '130', '116', '143', '276', '169', '36', '214', '244', '23', '25', '240', '103', '224', '81', '82', '218', '189', '176', '122', '239', '148', '121', '208', '140', '69', '70', '147', '220'}
Présents dans indicateur_emploi mais pas dans population : set()
Présents dans population mais pas dans valeur_prod_agricole : {'259', '281', '135', '173', '22', '72', '142', '119', '210', '132', '190', '180', '68', '198', '88', '94', '106', '278', '282', '174', '134', '27', '192', '183', '54', '163', '280', '85', '97', '236', '127', '65', '87', '17', '255', '203', '258', '79', '36', '63', '67', '84', '199', '240', '224', '82', '125', '50', '104', '239', '256', '270', '182', '243', '6', '5', '11', '126', '205', '167', '140', '69', '64', '264', '98', '150', '279', '187'}
Présents dans valeur_prod_agricole mais pas dans population : set()
Présents dans population mais pas dans culture_prod_poulet : {'259', '281', '135', '22', '72', '142', '132', '210', '190', '180', '88', '94', '278', '282', '192', '163', '280', '85', '127', '65', '87', '17', '258', '36', '84', '240', '224', '82', '125', '239', '270', '182', '243', '6', '5', '205', '140', '69', '64', '264', '279', '187'}
Présents dans culture_prod_poulet mais pas dans population : set()
Présents dans population mais pas dans bilan_alimentaire : {'259', '281', '135', '22', '142', '190', '180', '178', '88', '94', '278', '282', '26', '160', '192', '163', '280', '85', '61', '116', '65', '87', '17', '258', '36', '47', '200', '240', '224', '82', '218', '299', '125', '239', '270', '182', '243', '6', '5', '177', '205', '140', '69', '64', '264', '279', '187'}
Présents dans bilan_alimentaire mais pas dans population : set()

In [12]:
# Codes présents uniquement dans population
uniques_pop = codes_pop - (codes_sec | codes_indices | codes_indicateur_emploi |
                        codes_valeur_prod_agricole | codes_culture_prod_poulet |
                        codes_bilan_alimentaire)

# Afficher les country_code et zone correspondants
print("country_code et zone présents uniquement dans population :")
print(population[population['country_code'].isin(uniques_pop)][['country_code', 'zone']])

country_code et zone présents uniquement dans population :
    country_code                                          zone
28           125                                 Liechtenstein
39           135                                    Martinique
44           140                                        Monaco
65           163                        Îles Mariannes du Nord
84           182                                       Réunion
88           187  Ascension, Sainte-Hélène et Tristan da Cunha
92           190                      Saint-Pierre-et-Miquelon
94           192                                   Saint-Marin
108          205                             Sahara occidental
123           22                                         Aruba
128          224                       Îles Turques-et-Caïques
142          239                     Îles Vierges britanniques
143          240                      Îles Vierges américaines
144          243                         Îles Wallis-et-Futuna
152          258                                      Anguilla
153          259                          Îles Anglo-Normandes
155          264                                    Île de Man
157          270                                       Mayotte
162          278               Bonaire, Saint-Eustache et Saba
163          279                                       Curaçao
165          280            Sint Maarten (partie néerlandaise)
166          281               Saint-Martin (partie française)
167          282                              Saint-Barthélemy
175           36                                 Îles Caïmanes
203           65                      Îles Falkland (Malvinas)
207           69                              Guyane française
218           82                                     Gibraltar
223           87                                    Guadeloupe
224           88                                          Guam
230           94                                   Saint-Siège

In [13]:
def merge_all():
    df_merged = pd.merge(groupe_pays, population, left_on='code_pays', right_on='country_code', how='left', suffixes=('_pop', '_secu'))
    df_merged = pd.merge(df_merged, securite_alimentaire, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_secu'))
    df_merged = pd.merge(df_merged, indices_commerciaux, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_indices'))
    df_merged = pd.merge(df_merged, indicateur_emploi, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_emploi'))
    df_merged = pd.merge(df_merged, valeur_prod_agricole, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_valeur_prod_agricole'))
    df_merged = pd.merge(df_merged, culture_prod_poulet, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_culture_prod_poulet'))
    df_merged = pd.merge(df_merged, bilan_alimentaire, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_bilan_alimentaire'))
    return df_merged

df_merged = merge_all()
df_merged

,code_groupe_de_pays,groupe_de_pays,code_groupe_m49,code_pays,pays,code_m49,code_iso2,code_iso3,country_code,zone,...,zone_culture_prod_poulet,reserves,country_code_bilan_alimentaire,zone_bilan_alimentaire,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
0,5100,Afrique,2.0,107,Côte d'Ivoire,384.0,CI,CIV,107,Côte d'Ivoire,...,Côte d'Ivoire,89511.0,107,Côte d'Ivoire,72.0,0.0,1.0,72.0,71.0,0.0
1,5100,Afrique,2.0,114,Kenya,404.0,KE,KEN,114,Kenya,...,Kenya,57178.0,114,Kenya,69.0,0.0,1.0,69.0,69.0,1.0
2,5100,Afrique,2.0,122,Lesotho,426.0,LS,LSO,122,Lesotho,...,Lesotho,471.0,122,Lesotho,4.0,NaN,3.0,4.0,1.0,0.0
3,5100,Afrique,2.0,123,Libéria,430.0,LR,LBR,123,Libéria,...,Libéria,8031.0,123,Libéria,56.0,0.0,42.0,56.0,15.0,0.0
4,5100,Afrique,2.0,124,Libye,434.0,LY,LBY,124,Libye,...,Libye,36550.0,124,Libye,223.0,NaN,96.0,223.0,127.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2421,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,247,Yemen Dém,720.0,F247,F247,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2422,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,249,Yémen,887.0,YE,YEM,249,Yémen,...,Yémen,69039.0,249,Yémen,348.0,NaN,147.0,348.0,201.0,0.0
2423,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,299,Palestine,275.0,F299,PSE,299,Palestine,...,Palestine,7420.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2424,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,608,"Asie de l'Ouest, non spécifié",879.0,F608,F608,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2425,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",485.0,76,Palestine,274.0,F76,76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
def clean_df(df_merged):
    df_merged = df_merged.drop(columns=[
        'country_code_secu', 
        'country_code_indices',
        'country_code_emploi',
        'country_code_valeur_prod_agricole',
        'country_code_culture_prod_poulet',
        'country_code_bilan_alimentaire',
        'zone_secu',
        'zone_indices',
        'zone_emploi',
        'zone_valeur_prod_agricole',
        'zone_culture_prod_poulet',
        'zone_bilan_alimentaire',
        'code_iso3',
        'code_iso2',
        'code_m49',
        'code_groupe_m49',
        'code_pays',
        'zone'
    ])
    df_merged = df_merged.dropna(subset=['country_code'])
    return df_merged

df_merged = clean_df(df_merged)
df_merged

,code_groupe_de_pays,groupe_de_pays,pays,country_code,population_totale,besoins_energetiques_alimentaires_moyens_(kcal/personne/jour),densite_du_reseau_ferroviaire_(pour_100_km_carres_de_surface_totale_du_pays),"pib_par_habitant,_($_ppa_internationaux_constants_de_2017)",stabilite_politique_et_absence_de_violence/terrorisme_(indice),taux_de_dependance_a_l'egard_des_importations_cerealieres_(%)_(moyenne_sur_3_ans),...,valeur_des_importations_-_quantite_periode_de_reference,indicateur_emploi,production_brute_2014-2016_(millier_int$),reserves,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
0,5100,Afrique,Côte d'Ivoire,107,28915449.0,2233.0,0.2,6.161200e+09,-1.03,48.4,...,1432922.0,NaN,142705.0,89511.0,72.0,0.0,1.0,72.0,71.0,0.0
1,5100,Afrique,Kenya,114,52217334.0,2254.0,0.0,5.079900e+09,-1.01,47.8,...,2044179.0,NaN,132879.0,57178.0,69.0,0.0,1.0,69.0,69.0,1.0
2,5100,Afrique,Lesotho,122,2235727.0,2299.0,0.0,2.440900e+09,-0.25,100.0,...,282993.0,NaN,2.0,471.0,4.0,NaN,3.0,4.0,1.0,0.0
3,5100,Afrique,Libéria,123,5149463.0,2213.0,0.0,1.513800e+09,-0.31,71.8,...,309123.0,NaN,26665.0,8031.0,56.0,0.0,42.0,56.0,15.0,0.0
4,5100,Afrique,Libye,124,7045399.0,2384.0,0.0,1.166060e+10,-2.46,92.5,...,2956348.0,NaN,249303.0,36550.0,223.0,NaN,96.0,223.0,127.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",Oman,221,4522497.0,2446.0,0.0,3.757270e+10,0.42,87.7,...,3038247.0,NaN,12461.0,4830.0,90.0,22.0,116.0,90.0,7.0,10.0
2418,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",Türkiye,223,86091692.0,2410.0,1.3,2.864960e+10,-1.14,39.9,...,9790827.0,4641.95,4108838.0,379349.0,1686.0,559.0,45.0,1686.0,2201.0,1.0
2419,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",Émirats arabes unis,225,9448524.0,2666.0,0.3,6.659040e+10,0.59,96.6,...,14258202.0,116.72,101526.0,24630.0,463.0,86.0,493.0,463.0,54.0,-1.0
2422,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",Yémen,249,36134863.0,2192.0,0.0,0.000000e+00,-2.65,88.5,...,2824848.0,NaN,370781.0,69039.0,348.0,NaN,147.0,348.0,201.0,0.0
2423,5828,"Western Asia (exc. Armenia, Azerbaijan, Cyprus...",Palestine,299,5069692.0,2222.0,0.0,5.423700e+09,-2.02,95.2,...,1677195.0,60.52,92052.0,7420.0,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
def save_merge_csv(df_merged):
    df_merged.to_csv("../export/final_data_2020.csv", index=False, sep=",", encoding="utf-8-sig")
    print("Final data for 2020 transformed and saved successfully.")

save_merge_csv(df_merged)

Final data for 2020 transformed and saved successfully.