In [25]:
import pandas as pd

In [26]:
indices_commerciaux = pd.read_csv("../export/indices_commerciaux_2020.csv", sep=",", dtype={"country_code": str})
population = pd.read_csv("../export/population_2020.csv", sep=",", dtype={"country_code": str})
securite_alimentaire = pd.read_csv("../export/securite_alimentaire_2020.csv", sep=",", dtype={"country_code": str})
groupe_pays = pd.read_csv("../export/groupe_pays.csv", sep=",", dtype={"code_pays": str})
indicateur_emploi = pd.read_csv("../export/indicateur_emploi_2020.csv", sep=",", dtype={"country_code": str})
valeur_prod_agricole = pd.read_csv("../export/valeur_prod_agricole_2020.csv", sep=",", dtype={"country_code": str})
culture_prod_poulet = pd.read_csv("../export/culture_prod_poulet_2020.csv", sep=",", dtype={"country_code": str})
bilan_alimentaire = pd.read_csv("../export/bilan_alimentaire_2020.csv", sep=",", dtype={"country_code": str})

In [27]:
indices_commerciaux = indices_commerciaux.drop(columns=[
    "indice_de_valeur_unitaire_a_l'import_(2014-2016_=_100)", 
    "indice_de_valeur_unitaire_a_l'export_(2014-2016_=_100)",
    "indice_de_quantite_d'exportation_(2014-2016_=_100)",
    "indice_de_quantite_d'importation_(2014-2016_=_100)",
    "indice_de_valeur_d'exportation_(2014-2016_=_100)",
    "indice_de_valeur_des_importations_(2014-2016_=_100)",
])
indices_commerciaux

,country_code,zone,valeur_des_exportations_-_prix_periode_de_reference,valeur_des_exportations_-_quantite_periode_de_reference,valeur_des_importations_-_prix_periode_de_reference,valeur_des_importations_-_quantite_periode_de_reference
0,1,Arménie,394790.0,285986.0,848369.0,520384.0
1,10,Australie,25054864.0,35414918.0,10178035.0,14581857.0
2,100,Inde,31528384.0,26102565.0,21229798.0,20967386.0
3,101,Indonésie,34787544.0,30565911.0,19865540.0,13710859.0
4,102,Iran (République islamique d'),7868343.0,3309283.0,9822524.0,9349679.0
...,...,...,...,...,...,...
190,95,Honduras,2447891.0,2110506.0,1442149.0,1301384.0
191,96,Chine - RAS de Hong-Kong,3559741.0,11199521.0,13903213.0,22458043.0
192,97,Hongrie,8194725.0,6691580.0,4996786.0,4416827.0
193,98,Croatie,1826101.0,1309198.0,2897383.0,2286200.0
194,99,Islande,49734.0,44752.0,486216.0,410563.0

In [28]:
population = population.drop(columns=["femmes", "hommes", "population_rurale", "population_urbaine"])
population

    country_code                            zone  population_totale
0              1                         Arménie       2.890892e+06
1             10                       Australie       2.574379e+07
2            100                            Inde       1.402618e+09
3            101                       Indonésie       2.748149e+08
4            102  Iran (République islamique d')       8.772344e+07
..           ...                             ...                ...
231           95                        Honduras       1.011964e+07
232           96        Chine - RAS de Hong-Kong       7.490235e+06
233           97                         Hongrie       9.749457e+06
234           98                         Croatie       3.953958e+06
235           99                         Islande       3.666140e+05

[236 rows x 3 columns]

In [29]:

securite_alimentaire

,country_code,zone,besoins_energetiques_alimentaires_moyens_(kcal/personne/jour),densite_du_reseau_ferroviaire_(pour_100_km_carres_de_surface_totale_du_pays),"pib_par_habitant,_($_ppa_internationaux_constants_de_2017)","part_des_cereales,_des_racines_et_des_tubercules_dans_les_apports_energetiques_alimentaires_(%)_(moyenne_sur_3_ans)",pourcentage_des_terres_arables_amenagees_pour_l'irrigation_(%)_(moyenne_sur_3_ans),stabilite_politique_et_absence_de_violence/terrorisme_(indice),suffisance_des_apports_energetiques_alimentaires_moyens_(%)_(moyenne_sur_3_ans),taux_de_dependance_a_l'egard_des_importations_cerealieres_(%)_(moyenne_sur_3_ans),valeur_des_importations_alimentaires_par_rapport_aux_exportations_totales_de_marchandises_(%)_(moyenne_sur_3_ans),variabilite_des_disponibilites_alimentaires_par_habitant_(kcal/personne/jour)
0,1,Arménie,2420.0,2.3,15889.3,39.0,7.3,-0.77,133.0,85.9,24.0,51.0
1,10,Australie,2493.0,0.0,56298.2,23.0,0.3,0.86,140.0,-163.2,5.0,31.0
2,100,Inde,2325.0,2.1,7436.1,54.0,25.1,-0.84,110.0,-8.9,6.0,20.0
3,101,Indonésie,2311.0,0.0,12523.2,57.0,3.6,-0.46,126.0,15.3,8.0,43.0
4,102,Iran (République islamique d'),2376.0,0.5,14468.6,51.0,5.9,-1.70,122.0,47.8,14.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...
199,95,Honduras,2304.0,0.0,5672.2,43.0,0.8,-0.45,115.0,65.3,18.0,8.0
200,96,Chine - RAS de Hong-Kong,2432.0,0.0,61328.4,27.0,1.0,0.06,128.0,100.0,4.0,73.0
201,97,Hongrie,2527.0,8.2,35937.8,28.0,2.1,0.84,133.0,-91.8,4.0,26.0
202,98,Croatie,2492.0,3.0,31124.0,28.0,0.8,0.61,129.0,-51.0,17.0,34.0
203,99,Islande,2561.0,0.0,59801.9,28.0,0.0,1.37,142.0,92.5,10.0,44.0

In [30]:
groupe_pays

,code_groupe_de_pays,groupe_de_pays,code_groupe_m49,code_pays,pays,code_m49,code_iso2,code_iso3
0,5100,Afrique,2,107,Côte d'Ivoire,384.0,CI,CIV
1,5100,Afrique,2,114,Kenya,404.0,KE,KEN
2,5100,Afrique,2,122,Lesotho,426.0,LS,LSO
3,5100,Afrique,2,123,Libéria,430.0,LR,LBR
4,5100,Afrique,2,124,Libye,434.0,LY,LBY
...,...,...,...,...,...,...,...,...
293,5000,Monde,1,5,Samoa américaines,16.0,AS,ASM
294,5000,Monde,1,544,"Pays en voie de développement, non spécifié",529.0,F544,F544
295,5000,Monde,1,613,"Océanie, non spécifié",527.0,F613,F613
296,5000,Monde,1,618,"Polynésie, non spécifié",286.0,F618,F618
297,5000,Monde,1,70,Polynésie française,258.0,PF,PYF

In [31]:
indicateur_emploi = indicateur_emploi.rename(columns={"valeur": "indicateur_emploi"})
indicateur_emploi

   country_code                            zone  indicateur_emploi
0             1                         Arménie             361.06
1            10                       Australie             314.85
2           100                            Inde          171201.84
3           102  Iran (République islamique d')            3751.40
4           104                         Irlande              96.47
..          ...                             ...                ...
80            9                       Argentine              44.89
81           95                        Honduras             813.30
82           97                         Hongrie             191.54
83           98                         Croatie              90.35
84           99                         Islande               3.64

[85 rows x 3 columns]

In [32]:
valeur_prod_agricole

,country_code,zone,production_brute_2014-2016_(millier_int$)
0,1,Arménie,22694.0
1,10,Australie,2441665.0
2,100,Inde,8593866.0
3,101,Indonésie,6988395.0
4,102,Iran (République islamique d'),4669888.0
...,...,...,...
163,91,Guyana,81916.0
164,93,Haïti,14813.0
165,95,Honduras,359543.0
166,96,Chine - RAS de Hong-Kong,34299.0
167,99,Islande,17427.0

In [33]:
culture_prod_poulet

    country_code                            zone   reserves
0              1                         Arménie     4396.0
1             10                       Australie   100894.0
2            100                            Inde   824722.0
3            101                       Indonésie  3570142.0
4            102  Iran (République islamique d')  1010445.0
..           ...                             ...        ...
189           95                        Honduras    47038.0
190           96        Chine - RAS de Hong-Kong     4392.0
191           97                         Hongrie    30874.0
192           98                         Croatie    11360.0
193           99                         Islande      222.0

[194 rows x 3 columns]

In [34]:
bilan_alimentaire

,country_code,zone,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
0,1,Arménie,46.0,0.0,33.0,46.0,12.0,0.0
1,10,Australie,1242.0,42.0,2.0,1242.0,1282.0,0.0
2,100,Inde,4515.0,4.0,0.0,4516.0,4519.0,0.0
3,101,Indonésie,3682.0,0.0,0.0,3682.0,3683.0,1.0
4,102,Iran (République islamique d'),2438.0,6.0,3.0,2439.0,2441.0,0.0
...,...,...,...,...,...,...,...,...
184,95,Honduras,205.0,1.0,16.0,205.0,190.0,0.0
185,96,Chine - RAS de Hong-Kong,404.0,90.0,558.0,404.0,34.0,98.0
186,97,Hongrie,312.0,233.0,84.0,268.0,521.0,60.0
187,98,Croatie,68.0,16.0,25.0,68.0,70.0,12.0
188,99,Islande,11.0,0.0,2.0,11.0,9.0,0.0

In [35]:
# Récupérer les sets de country_code
codes_pop = set(population['country_code'])
codes_sec = set(securite_alimentaire['country_code'])
codes_indices = set(indices_commerciaux['country_code'])
codes_indicateur_emploi = set(indicateur_emploi['country_code'])
codes_valeur_prod_agricole = set(valeur_prod_agricole['country_code'])
codes_culture_prod_poulet = set(culture_prod_poulet['country_code'])
codes_bilan_alimentaire = set(bilan_alimentaire['country_code'])

# country_code présents dans population mais pas dans securite_alimentaire
manquants_dans_secu = codes_pop - codes_sec
print("Présents dans population mais pas dans securite_alimentaire :", manquants_dans_secu)

# country_code présents dans securite_alimentaire mais pas dans population
manquants_dans_pop = codes_sec - codes_pop
print("Présents dans securite_alimentaire mais pas dans population :", manquants_dans_pop)

# country_code présents dans indices_commerciaux mais pas dans population
manquants_dans_pop_indices = codes_pop - codes_indices
print("Présents dans population mais pas dans indices_commerciaux :", manquants_dans_pop_indices)

# country_code présents dans population mais pas dans indices_commerciaux
manquants_dans_indices_pop = codes_indices - codes_pop
print("Présents dans indices_commerciaux mais pas dans population :", manquants_dans_indices_pop)

# country_code présents dans population mais pas dans indicateur_emploi
manquants_dans_pop_indicateur_emploi = codes_pop - codes_indicateur_emploi
print("Présents dans population mais pas dans indicateur_emploi :", manquants_dans_pop_indicateur_emploi)

# country_code présents dans indicateur_emploi mais pas dans population
manquants_dans_indicateur_emploi_pop = codes_indicateur_emploi - codes_pop
print("Présents dans indicateur_emploi mais pas dans population :", manquants_dans_indicateur_emploi_pop)

# country_code présents dans population mais pas dans valeur_prod_agricole
manquants_dans_pop_valeur_prod_agricole = codes_pop - codes_valeur_prod_agricole
print("Présents dans population mais pas dans valeur_prod_agricole :", manquants_dans_pop_valeur_prod_agricole) 

# country_code présents dans valeur_prod_agricole mais pas dans population
manquants_dans_valeur_prod_agricole_pop = codes_valeur_prod_agricole - codes_pop
print("Présents dans valeur_prod_agricole mais pas dans population :", manquants_dans_valeur_prod_agricole_pop) 

# country_code présents dans population mais pas dans culture_prod_poulet
manquants_dans_pop_culture_prod_poulet = codes_pop - codes_culture_prod_poulet
print("Présents dans population mais pas dans culture_prod_poulet :", manquants_dans_pop_culture_prod_poulet)

# country_code présents dans culture_prod_poulet mais pas dans population
manquants_dans_culture_prod_poulet_pop = codes_culture_prod_poulet - codes_pop
print("Présents dans culture_prod_poulet mais pas dans population :", manquants_dans_culture_prod_poulet_pop)

# country_code présents dans population mais pas dans bilan_alimentaire
manquants_dans_pop_bilan_alimentaire = codes_pop - codes_bilan_alimentaire
print("Présents dans population mais pas dans bilan_alimentaire :", manquants_dans_pop_bilan_alimentaire)

# country_code présents dans bilan_alimentaire mais pas dans population
manquants_dans_bilan_alimentaire_pop = codes_bilan_alimentaire - codes_pop
print("Présents dans bilan_alimentaire mais pas dans population :", manquants_dans_bilan_alimentaire_pop)

Présents dans population mais pas dans securite_alimentaire : {'281', '182', '270', '243', '240', '87', '22', '282', '279', '258', '69', '142', '88', '224', '190', '82', '36', '140', '94', '135', '187', '205', '65', '259', '264', '192', '125', '278', '280', '163', '239', '64'}
Présents dans securite_alimentaire mais pas dans population : set()
Présents dans population mais pas dans indices_commerciaux : {'17', '281', '182', '270', '243', '240', '87', '177', '22', '5', '282', '279', '258', '351', '69', '142', '145', '88', '218', '85', '190', '224', '6', '82', '36', '140', '94', '135', '187', '205', '65', '259', '264', '192', '125', '278', '280', '127', '163', '239', '180'}
Présents dans indices_commerciaux mais pas dans population : set()
Présents dans population mais pas dans indicateur_emploi : {'191', '17', '148', '157', '181', '93', '90', '32', '45', '177', '129', '5', '258', '351', '8', '116', '277', '85', '190', '7', '131', '46', '6', '82', '169', '220', '217', '233', '101', '65', '121', '259', '213', '188', '72', '75', '132', '201', '163', '52', '166', '146', '64', '3', '235', '249', '120', '176', '168', '179', '53', '49', '66', '279', '69', '145', '219', '238', '212', '4', '135', '205', '197', '117', '125', '13', '37', '250', '96', '236', '189', '118', '229', '207', '35', '281', '244', '182', '123', '61', '47', '124', '185', '270', '178', '221', '273', '240', '103', '87', '208', '222', '39', '91', '122', '158', '33', '226', '109', '218', '160', '224', '276', '114', '36', '128', '140', '14', '209', '108', '175', '12', '130', '194', '2', '89', '127', '200', '70', '41', '147', '243', '144', '143', '107', '159', '156', '23', '25', '22', '282', '272', '214', '88', '193', '149', '195', '94', '187', '136', '74', '55', '264', '192', '16', '81', '278', '280', '227', '239', '165'}
Présents dans indicateur_emploi mais pas dans population : set()
Présents dans population mais pas dans valeur_prod_agricole : {'50', '97', '17', '281', '182', '256', '270', '243', '174', '240', '87', '11', '150', '63', '126', '22', '5', '282', '279', '258', '199', '134', '69', '54', '203', '79', '142', '198', '85', '190', '224', '88', '6', '82', '98', '36', '173', '140', '94', '210', '135', '187', '205', '65', '259', '68', '264', '72', '192', '132', '125', '255', '119', '278', '27', '183', '167', '106', '127', '280', '163', '239', '84', '236', '67', '104', '180', '64'}
Présents dans valeur_prod_agricole mais pas dans population : set()
Présents dans population mais pas dans culture_prod_poulet : {'17', '281', '182', '270', '243', '240', '87', '22', '5', '282', '279', '258', '69', '142', '88', '224', '85', '190', '6', '82', '36', '140', '94', '210', '135', '187', '205', '65', '259', '264', '72', '192', '132', '125', '278', '280', '127', '163', '239', '84', '180', '64'}
Présents dans culture_prod_poulet mais pas dans population : set()
Présents dans population mais pas dans bilan_alimentaire : {'17', '281', '182', '61', '47', '270', '243', '178', '240', '87', '177', '22', '5', '282', '279', '258', '69', '142', '116', '88', '218', '299', '190', '85', '160', '224', '6', '82', '36', '140', '94', '135', '187', '205', '65', '26', '259', '264', '192', '125', '278', '280', '163', '239', '200', '180', '64'}
Présents dans bilan_alimentaire mais pas dans population : set()

In [36]:
# Codes présents uniquement dans population
uniques_pop = codes_pop - (codes_sec | codes_indices | codes_indicateur_emploi |
                        codes_valeur_prod_agricole | codes_culture_prod_poulet |
                        codes_bilan_alimentaire)

# Afficher les country_code et zone correspondants
print("country_code et zone présents uniquement dans population :")
print(population[population['country_code'].isin(uniques_pop)][['country_code', 'zone']])

country_code et zone présents uniquement dans population :
    country_code                                          zone
28           125                                 Liechtenstein
39           135                                    Martinique
44           140                                        Monaco
65           163                        Îles Mariannes du Nord
84           182                                       Réunion
88           187  Ascension, Sainte-Hélène et Tristan da Cunha
92           190                      Saint-Pierre-et-Miquelon
94           192                                   Saint-Marin
108          205                             Sahara occidental
123           22                                         Aruba
128          224                       Îles Turques-et-Caïques
142          239                     Îles Vierges britanniques
143          240                      Îles Vierges américaines
144          243                         Îles Wallis-et-Futuna
152          258                                      Anguilla
153          259                          Îles Anglo-Normandes
155          264                                    Île de Man
157          270                                       Mayotte
162          278               Bonaire, Saint-Eustache et Saba
163          279                                       Curaçao
165          280            Sint Maarten (partie néerlandaise)
166          281               Saint-Martin (partie française)
167          282                              Saint-Barthélemy
175           36                                 Îles Caïmanes
203           65                      Îles Falkland (Malvinas)
207           69                              Guyane française
218           82                                     Gibraltar
223           87                                    Guadeloupe
224           88                                          Guam
230           94                                   Saint-Siège

In [37]:
def merge_all():
    df_merged = pd.merge(groupe_pays, population, left_on='code_pays', right_on='country_code', how='left', suffixes=('_pop', '_secu'))
    df_merged = pd.merge(df_merged, securite_alimentaire, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_secu'))
    df_merged = pd.merge(df_merged, indices_commerciaux, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_indices'))
    df_merged = pd.merge(df_merged, indicateur_emploi, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_emploi'))
    df_merged = pd.merge(df_merged, valeur_prod_agricole, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_valeur_prod_agricole'))
    df_merged = pd.merge(df_merged, culture_prod_poulet, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_culture_prod_poulet'))
    df_merged = pd.merge(df_merged, bilan_alimentaire, left_on='code_pays', right_on='country_code', how='left', suffixes=('', '_bilan_alimentaire'))
    return df_merged

df_merged = merge_all()
df_merged

,code_groupe_de_pays,groupe_de_pays,code_groupe_m49,code_pays,pays,code_m49,code_iso2,code_iso3,country_code,zone,...,zone_culture_prod_poulet,reserves,country_code_bilan_alimentaire,zone_bilan_alimentaire,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
0,5100,Afrique,2,107,Côte d'Ivoire,384.0,CI,CIV,107,Côte d'Ivoire,...,Côte d'Ivoire,89511.0,107,Côte d'Ivoire,72.0,0.0,1.0,72.0,71.0,0.0
1,5100,Afrique,2,114,Kenya,404.0,KE,KEN,114,Kenya,...,Kenya,57178.0,114,Kenya,69.0,0.0,1.0,69.0,69.0,1.0
2,5100,Afrique,2,122,Lesotho,426.0,LS,LSO,122,Lesotho,...,Lesotho,471.0,122,Lesotho,4.0,NaN,3.0,4.0,1.0,0.0
3,5100,Afrique,2,123,Libéria,430.0,LR,LBR,123,Libéria,...,Libéria,8031.0,123,Libéria,56.0,0.0,42.0,56.0,15.0,0.0
4,5100,Afrique,2,124,Libye,434.0,LY,LBY,124,Libye,...,Libye,36550.0,124,Libye,223.0,NaN,96.0,223.0,127.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,5000,Monde,1,5,Samoa américaines,16.0,AS,ASM,5,Samoa américaines,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,5000,Monde,1,544,"Pays en voie de développement, non spécifié",529.0,F544,F544,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,5000,Monde,1,613,"Océanie, non spécifié",527.0,F613,F613,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,5000,Monde,1,618,"Polynésie, non spécifié",286.0,F618,F618,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,5000,Monde,1,70,Polynésie française,258.0,PF,PYF,70,Polynésie française,...,Polynésie française,325.0,70,Polynésie française,17.0,NaN,17.0,14.0,1.0,1.0

In [38]:
def clean_df(df_merged):
    df_merged = df_merged.drop(columns=[
        'country_code_secu', 
        'country_code_indices',
        'country_code_emploi',
        'country_code_valeur_prod_agricole',
        'country_code_culture_prod_poulet',
        'country_code_bilan_alimentaire',
        'zone_secu',
        'zone_indices',
        'zone_emploi',
        'zone_valeur_prod_agricole',
        'zone_culture_prod_poulet',
        'zone_bilan_alimentaire',
        'code_iso3',
        'code_iso2',
        'code_m49',
        'code_groupe_m49',
        'code_pays',
        'zone'
    ])
    df_merged = df_merged.dropna(subset=['country_code'])
    return df_merged

df_merged = clean_df(df_merged)
df_merged

,code_groupe_de_pays,groupe_de_pays,pays,country_code,population_totale,besoins_energetiques_alimentaires_moyens_(kcal/personne/jour),densite_du_reseau_ferroviaire_(pour_100_km_carres_de_surface_totale_du_pays),"pib_par_habitant,_($_ppa_internationaux_constants_de_2017)","part_des_cereales,_des_racines_et_des_tubercules_dans_les_apports_energetiques_alimentaires_(%)_(moyenne_sur_3_ans)",pourcentage_des_terres_arables_amenagees_pour_l'irrigation_(%)_(moyenne_sur_3_ans),...,valeur_des_importations_-_quantite_periode_de_reference,indicateur_emploi,production_brute_2014-2016_(millier_int$),reserves,disponibilite_interieure,exportations_-_quantite,importations_-_quantite,nourriture,production,variation_de_stock
0,5100,Afrique,Côte d'Ivoire,107,28915449.0,2233.0,0.2,6161.2,70.0,0.2,...,1432922.0,NaN,142705.0,89511.0,72.0,0.0,1.0,72.0,71.0,0.0
1,5100,Afrique,Kenya,114,52217334.0,2254.0,0.0,5079.9,53.0,0.3,...,2044179.0,NaN,132879.0,57178.0,69.0,0.0,1.0,69.0,69.0,1.0
2,5100,Afrique,Lesotho,122,2235727.0,2299.0,0.0,2440.9,67.0,0.1,...,282993.0,NaN,2.0,471.0,4.0,NaN,3.0,4.0,1.0,0.0
3,5100,Afrique,Libéria,123,5149463.0,2213.0,0.0,1513.8,72.0,0.0,...,309123.0,NaN,26665.0,8031.0,56.0,0.0,42.0,56.0,15.0,0.0
4,5100,Afrique,Libye,124,7045399.0,2384.0,0.0,11660.6,41.0,0.2,...,2956348.0,NaN,249303.0,36550.0,223.0,NaN,96.0,223.0,127.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,5000,Monde,Îles Wallis-et-Futuna,243,11616.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,5000,Monde,Samoa,244,211944.0,2335.0,0.0,6689.7,38.0,0.0,...,82663.0,NaN,625.0,386.0,16.0,NaN,16.0,16.0,0.0,0.0
292,5000,Monde,Îles Cook,47,15643.0,0.0,0.0,0.0,0.0,0.0,...,27954.0,NaN,80.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN
293,5000,Monde,Samoa américaines,5,49761.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,5000,Monde,Polynésie française,70,279209.0,2440.0,0.0,0.0,35.0,0.3,...,363838.0,NaN,1100.0,325.0,17.0,NaN,17.0,14.0,1.0,1.0

In [39]:
def save_merge_csv(df_merged):
    df_merged.to_csv("../export/final_data_2020.csv", index=False, sep=",", encoding="utf-8-sig")
    print("Final data for 2020 transformed and saved successfully.")

save_merge_csv(df_merged)

Final data for 2020 transformed and saved successfully.